# Site settings
title: Wild Gums
email: contact@wildgums.com
description: "WildGums Software"
baseurl: ""
url: "http://www.wildgums.com"
include: [_colorpicker.js, _handlebars.js]

# Build settings
markdown: kramdown
permalink: pretty

gems:
  - jekyll-redirect-from
  
footer-phone: "+61 1300 737 500"
footer-email: "contact@wildgums.com"
footer-copyright: "Wild Gums. All Rights Reserved."